name: UltrahardMinecraft
version: ${project.version}
main: com.giornosmp.ultrahardminecraft.UltrahardMinecraft
api-version: 1.16
authors: [ Giorno420 ]
description: Makes Minecraft waay harder
website: https://giorno.is-a-good.dev
